=== UO265181/sew-proyecto/entrega/proyecto/xml/rutas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.uniovi.es"
    xmlns="http://www.uniovi.es"
    elementFormDefault="qualified">

    <xs:element name="rutas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ruta" minOccurs="3" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element minOccurs="1" maxOccurs="1" ref="duracion" />
                            <xs:element name="agencia" minOccurs="0" maxOccurs="1" type="xs:string" />
                            <xs:element name="descripcion" type="xs:string" />
                            <xs:element name="personas" type="xs:string" />
                            <xs:element minOccurs="1" maxOccurs="1" ref="inicio" />
                            <xs:element minOccurs="1" maxOccurs="1" ref="referencias" />
                            <xs:element name="hitos">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element minOccurs="3" maxOccurs="unbounded" ref="hito" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="planimetria" type="xs:string" />
                            <xs:element name="altimetria" type="xs:string" />
                        </xs:sequence>
                        <xs:attribute name="nombre" use="required" type="xs:string" />
                        <xs:attribute name="tipo" use="required" type="xs:string" />
                        <xs:attribute name="medio_transporte" use="required" type="xs:string" />
                        <xs:attribute name="recomendacion" use="required" type="xs:integer" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="duracion">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:decimal">
                    <xs:attribute name="unidades"
                        type="xs:string"
                        use="required" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="referencias">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="referencia" minOccurs="3"
                    maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="url" type="xs:anyURI"
                                    use="required" />
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="inicio">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="fecha" type="xs:date" />
                <xs:element name="hora" type="xs:time" />
                <xs:element name="lugar" type="xs:string" />
                <xs:element name="direccion" type="xs:string" />
                <xs:element minOccurs="1" maxOccurs="1" ref="coordenadas" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="hito">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="descripcion" type="xs:string" />
                <xs:element minOccurs="1" maxOccurs="1"
                    ref="coordenadas" />
                <xs:element minOccurs="1" maxOccurs="1" ref="distancia" />
                <xs:element minOccurs="1" maxOccurs="1" ref="galeria_fotos" />
                <xs:element minOccurs="0" maxOccurs="1" ref="galeria_videos" />
            </xs:sequence>
            <xs:attribute name="nombre" use="required"
                type="xs:string" />
        </xs:complexType>
    </xs:element>

    <xs:element name="distancia">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:decimal">
                    <xs:attribute name="unidades"
                        type="xs:string"
                        use="required" />
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="galeria_fotos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="foto"
                    type="xs:string"
                    minOccurs="1"
                    maxOccurs="5" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="galeria_videos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="video"
                    type="xs:string"
                    minOccurs="0"
                    maxOccurs="3" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="coordenadas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="longitud"
                    type="xs:decimal" />
                <xs:element name="latitud"
                    type="xs:decimal" />
                <xs:element name="altitud"
                    type="xs:decimal" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>


</xs:schema>

=== UO265181/sew-proyecto/entrega/proyecto/xml/rutas.xml
<?xml version="1.0" encoding="UTF-8"?>


<rutas xmlns="http://www.uniovi.es"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.uniovi.es rutas.xsd">
    <ruta nombre="TODO" tipo="Arquitectura y monumentos" medio_transporte="A pie" recomendacion="8">
        <duracion unidades="horas">4</duracion>
        <agencia>NaturAller</agencia>
        <descripcion>Esta ruta te llevará a conocer algunos de los monumentos prerrománicos más
            importantes del concejo.</descripcion>
        <personas>Cualquiera</personas>
        <inicio>
            <fecha>2023-06-10</fecha>
            <hora>10:00:00</hora>
            <lugar>Plaza del ayuntamiento </lugar>
            <direccion>Calle Foncalada </direccion>
            <coordenadas>
                <longitud>-5.852826</longitud>
                <latitud>43.361300</latitud>
                <altitud>100</altitud>
            </coordenadas>
        </inicio>

        <referencias>
            <referencia url="https://es.wikipedia.org/wiki/Foncalada">Foncalada en Wikipedia</referencia>
            <referencia url="http://prerromanicoasturiano.es/">Prerrománico Asturiano</referencia>
            <referencia
                url="https://www.turismoasturias.es/descubre/cultura/prerromanico-en-asturias">Turismo
                Asturias: Prerrománico en Asturias</referencia>
        </referencias>
        <hitos>
            <hito nombre="TODO">
                <descripcion>Conocida como la "Iglesia de Santullano", este monumento es uno de los
                    más importantes del arte prerrománico asturiano.</descripcion>
                <coordenadas>
                    <longitud>-5.864891</longitud>
                    <latitud>43.364939</latitud>
                    <altitud>130</altitud>
                </coordenadas>
                <distancia unidades="kilometros">0.5</distancia>
                <galeria_fotos>
                    <foto>san_julian_1.jpg</foto>
                    <foto>san_julian_2.jpg</foto>
                </galeria_fotos>
                <galeria_videos>
                    <video>https://www.youtube.com/watch?v=ZD8gVnZZ2Ko</video>
                </galeria_videos>
            </hito>
            <hito nombre="TODO">
                <descripcion>Construida en el siglo IX, esta iglesia palatina es una de las obras
                    más destacadas del arte asturiano prerrománico.</descripcion>
                <coordenadas>
                    <longitud>-5.846508</longitud>
                    <latitud>43.375942</latitud>
                    <altitud>310</altitud>
                </coordenadas>
                <distancia unidades="kilometros">0.5</distancia>
                <galeria_fotos>
                    <foto>santa_maria_1.jpg</foto>
                    <foto>santa_maria_2.jpg</foto>
                </galeria_fotos>
                <galeria_videos>
                    <video>https://www.youtube.com/watch?v=JDfTft3jX30</video>
                </galeria_videos>
            </hito>
            <hito nombre="TODO">
                <descripcion>Construida en el siglo IX, esta iglesia palatina es una de las obras
                    más destacadas del arte asturiano prerrománico.</descripcion>
                <coordenadas>
                    <longitud>-5.846508</longitud>
                    <latitud>43.375942</latitud>
                    <altitud>310</altitud>
                </coordenadas>
                <distancia unidades="kilometros">0.5</distancia>
                <galeria_fotos>
                    <foto>santa_maria_1.jpg</foto>
                    <foto>santa_maria_2.jpg</foto>
                </galeria_fotos>
                <galeria_videos>
                    <video>https://www.youtube.com/watch?v=JDfTft3jX30</video>
                </galeria_videos>
            </hito>
        </hitos>
        <planimetria></planimetria>
        <altimetria></altimetria>
    </ruta>

    <ruta nombre="ruta 2" tipo="Arquitectura y monumentos" medio_transporte="A pie" recomendacion="8">
        <duracion unidades="horas">4</duracion>
        <agencia>NaturAller</agencia>
        <descripcion>Esta ruta te llevará a conocer algunos de los monumentos prerrománicos más
            importantes del concejo.</descripcion>
        <personas>Cualquiera</personas>
        <inicio>
            <fecha>2023-06-10</fecha>
            <hora>10:00:00</hora>
            <lugar>Plaza del ayuntamiento </lugar>
            <direccion>Calle Foncalada </direccion>
            <coordenadas>
                <longitud>-5.852826</longitud>
                <latitud>43.361300</latitud>
                <altitud>100</altitud>
            </coordenadas>
        </inicio>

        <referencias>
            <referencia url="https://es.wikipedia.org/wiki/Foncalada">Foncalada en Wikipedia</referencia>
            <referencia url="http://prerromanicoasturiano.es/">Prerrománico Asturiano</referencia>
            <referencia
                url="https://www.turismoasturias.es/descubre/cultura/prerromanico-en-asturias">Turismo
                Asturias: Prerrománico en Asturias</referencia>
        </referencias>
        <hitos>
            <hito nombre="ruta 3">
                <descripcion>Conocida como la "Iglesia de Santullano", este monumento es uno de los
                    más importantes del arte prerrománico asturiano.</descripcion>
                <coordenadas>
                    <longitud>-5.864891</longitud>
                    <latitud>43.364939</latitud>
                    <altitud>130</altitud>
                </coordenadas>
                <distancia unidades="kilometros">0.5</distancia>
                <galeria_fotos>
                    <foto>san_julian_1.jpg</foto>
                    <foto>san_julian_2.jpg</foto>
                </galeria_fotos>
                <galeria_videos>
                    <video>https://www.youtube.com/watch?v=ZD8gVnZZ2Ko</video>
                </galeria_videos>
            </hito>
            <hito nombre="TODO">
                <descripcion>Construida en el siglo IX, esta iglesia palatina es una de las obras
                    más destacadas del arte asturiano prerrománico.</descripcion>
                <coordenadas>
                    <longitud>-5.846508</longitud>
                    <latitud>43.375942</latitud>
                    <altitud>310</altitud>
                </coordenadas>
                <distancia unidades="kilometros">0.5</distancia>
                <galeria_fotos>
                    <foto>santa_maria_1.jpg</foto>
                    <foto>santa_maria_2.jpg</foto>
                </galeria_fotos>
                <galeria_videos>
                    <video>https://www.youtube.com/watch?v=JDfTft3jX30</video>
                </galeria_videos>
            </hito>
            <hito nombre="TODO">
                <descripcion>Construida en el siglo IX, esta iglesia palatina es una de las obras
                    más destacadas del arte asturiano prerrománico.</descripcion>
                <coordenadas>
                    <longitud>-5.846508</longitud>
                    <latitud>43.375942</latitud>
                    <altitud>310</altitud>
                </coordenadas>
                <distancia unidades="kilometros">0.5</distancia>
                <galeria_fotos>
                    <foto>santa_maria_1.jpg</foto>
                    <foto>santa_maria_2.jpg</foto>
                </galeria_fotos>
                <galeria_videos>
                    <video>https://www.youtube.com/watch?v=JDfTft3jX30</video>
                </galeria_videos>
            </hito>
        </hitos>
        <planimetria></planimetria>
        <altimetria></altimetria>
    </ruta>

    <ruta nombre="TODO" tipo="Arquitectura y monumentos" medio_transporte="A pie" recomendacion="8">
        <duracion unidades="horas">4</duracion>
        <agencia>NaturAller</agencia>
        <descripcion>Esta ruta te llevará a conocer algunos de los monumentos prerrománicos más
            importantes del concejo.</descripcion>
        <personas>Cualquiera</personas>
        <inicio>
            <fecha>2023-06-10</fecha>
            <hora>10:00:00</hora>
            <lugar>Plaza del ayuntamiento </lugar>
            <direccion>Calle Foncalada </direccion>
            <coordenadas>
                <longitud>-5.852826</longitud>
                <latitud>43.361300</latitud>
                <altitud>100</altitud>
            </coordenadas>
        </inicio>

        <referencias>
            <referencia url="https://es.wikipedia.org/wiki/Foncalada">Foncalada en Wikipedia</referencia>
            <referencia url="http://prerromanicoasturiano.es/">Prerrománico Asturiano</referencia>
            <referencia
                url="https://www.turismoasturias.es/descubre/cultura/prerromanico-en-asturias">Turismo
                Asturias: Prerrománico en Asturias</referencia>
        </referencias>
        <hitos>
            <hito nombre="TODO">
                <descripcion>Conocida como la "Iglesia de Santullano", este monumento es uno de los
                    más importantes del arte prerrománico asturiano.</descripcion>
                <coordenadas>
                    <longitud>-5.864891</longitud>
                    <latitud>43.364939</latitud>
                    <altitud>130</altitud>
                </coordenadas>
                <distancia unidades="kilometros">0.5</distancia>
                <galeria_fotos>
                    <foto>san_julian_1.jpg</foto>
                    <foto>san_julian_2.jpg</foto>
                </galeria_fotos>
                <galeria_videos>
                    <video>https://www.youtube.com/watch?v=ZD8gVnZZ2Ko</video>
                </galeria_videos>
            </hito>
            <hito nombre="TODO">
                <descripcion>Construida en el siglo IX, esta iglesia palatina es una de las obras
                    más destacadas del arte asturiano prerrománico.</descripcion>
